name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          git clone https://github.com/DrKLO/Telegram.git $HOME/telegram-android
          cd $HOME/telegram-android
          docker build -t telegram-build .
          docker run --rm -v "$PWD":/home/source telegram-build
  
      - name: Actions apk
        uses: actions/upload-artifact@v3
        with:
          name: upload apk
          path: /apk/afat/standalone/app.apk
